### ISSUE TITLE
Compile error formatted inconsistently when query results open

### ISSUE THREAD

**Issue by dwl285** [dataform-co/dataform-web-tracking#143] opened 2019-06-18 10:45 UTC
![PastedGraphic-2.png](https://codetreeusercontent.s3.amazonaws.com/uploads/b0dceea6-b7c8-4d5c-976b-cfdee17fff1f/PastedGraphic-2.png)

**Comment by lewish** [comment] 2019-06-21 14:30
Duplicate of dataform-co/dataform-co#433

**Closed by lewish** 2019-06-21 14:30 UTC
