### ISSUE TITLE
Add amount of data to be processed in query validation

### ISSUE THREAD

**Issue by G2H** [dataform-co/dataform-web-tracking#125] opened 2019-03-20 14:47 UTC
We currently show the user a validation block to indicate if the query is going to run or not.

It would be great to also add the amount of data that's going to be processed, similar to what's being shown on the bigquery ui

**Comment by lewish** [comment] 2019-06-24 13:01
Duplicate of #18

**Closed by lewish** 2019-06-24 13:01 UTC
Labels: P3
